# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omm_service.proto\x12\x13\x64istributed_banking\"e\n\x0eRequestMessage\x12\x10\n\x08\x62rcustid\x18\x01 \x01(\x05\x12\x10\n\x08\x63usreqid\x18\x02 \x01(\x05\x12\x11\n\tinterface\x18\x03 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\x05\x12\r\n\x05\x63lock\x18\x05 \x01(\x05\"T\n\x0fResponseMessage\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x63lock\x18\x04 \x01(\x05\x32\xeb\x03\n\x0e\x43ommunications\x12[\n\x0cqueryBalance\x12#.distributed_banking.RequestMessage\x1a$.distributed_banking.ResponseMessage\"\x00\x12[\n\x0c\x64\x65positMoney\x12#.distributed_banking.RequestMessage\x1a$.distributed_banking.ResponseMessage\"\x00\x12\\\n\rwithdrawMoney\x12#.distributed_banking.RequestMessage\x1a$.distributed_banking.ResponseMessage\"\x00\x12_\n\x10propagateDeposit\x12#.distributed_banking.RequestMessage\x1a$.distributed_banking.ResponseMessage\"\x00\x12`\n\x11porpagateWithdraw\x12#.distributed_banking.RequestMessage\x1a$.distributed_banking.ResponseMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTMESSAGE']._serialized_start=43
  _globals['_REQUESTMESSAGE']._serialized_end=144
  _globals['_RESPONSEMESSAGE']._serialized_start=146
  _globals['_RESPONSEMESSAGE']._serialized_end=230
  _globals['_COMMUNICATIONS']._serialized_start=233
  _globals['_COMMUNICATIONS']._serialized_end=724
# @@protoc_insertion_point(module_scope)
